modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="silentvalkyrieremaster"
version="1.0.0"
displayName="SilentValkyrieremaster"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Silent Experience, MCreator"

[[dependencies.silentvalkyrieremaster]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




